export const HIEMPSAL_WORKING_HOURS =
    process.env.NEXT_PUBLIC_HIEMPSAL_WORKING_HOURS;
export const HIEMPSAL_PHONE_NUMBER =
    process.env.NEXT_PUBLIC_HIEMPSAL_PHONE_NUMBER;
export const HIEMPSAL_EMAIL = process.env.NEXT_PUBLIC_HIEMPSAL_WORKING_HOURS;
